version: '3'
services:
  php:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teststogo-db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
